# Generated by Django 5.2.1 on 2025-07-15 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='curso',
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
