# Generated by Django 5.2.1 on 2025-12-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdentidadeVisual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor_principal', models.CharField(default='#005EFF', max_length=7)),
                ('cor_secundaria', models.CharField(default='#005EFF', max_length=7)),
                ('cor_hover', models.CharField(default='#005EFF', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='galeria_sobre/')),
            ],
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200, null=True)),
                ('frase_inicio', models.CharField(blank=True, max_length=255, null=True)),
                ('o_que_e_site_titulo', models.CharField(blank=True, max_length=1000, null=True)),
                ('o_que_e_o_site', models.CharField(blank=True, max_length=1000, null=True)),
                ('saiba_mais', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capa', models.ImageField(blank=True, null=True, upload_to='administracao_page/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='livro_pdf')),
                ('titulo', models.CharField(blank=True, max_length=200, null=True)),
                ('tipo', models.CharField(blank=True, max_length=200, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pagina', models.IntegerField()),
                ('pagina', models.ImageField(upload_to='paginas_livro/')),
            ],
            options={
                'ordering': ['numero_pagina'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('contato', models.EmailField(blank=True, max_length=254, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
            ],
        ),
        migrations.CreateModel(
            name='Sobre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paginaTitulo', models.TextField(max_length=200)),
                ('sobre_nos', models.TextField()),
                ('secaoTitulo', models.TextField(max_length=200)),
                ('sobre_o_livro', models.TextField()),
                ('galeria', models.ManyToManyField(related_name='galerias', to='livro3d.image')),
                ('membros', models.ManyToManyField(to='livro3d.membro')),
            ],
        ),
    ]
