# Generated by Django 5.2.1 on 2025-12-19 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro3d', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='imagem',
            field=models.ImageField(upload_to='galeria/'),
        ),
    ]
