# Generated by Django 5.2.1 on 2025-07-15 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro3d', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='galeria_url',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='leia_o_livro_url',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='saiba_mais_url',
        ),
        migrations.AddField(
            model_name='homepage',
            name='fraseInicio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='oqueeosite',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
