# Generated by Django 5.2.1 on 2025-12-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro3d', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='index',
            name='saiba_mais',
        ),
        migrations.AddField(
            model_name='site',
            name='saiba_mais_footer',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
