# Generated by Django 5.2.1 on 2025-12-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro3d', '0002_remove_index_saiba_mais_site_saiba_mais_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='divosoria',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='index',
            name='divosoria_texto',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='index',
            name='sessao_texto',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='index',
            name='sessao_titulo',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
