# Generated by Django 5.2.1 on 2025-07-15 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro3d', '0002_remove_homepage_galeria_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModoLeitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo_leitura', models.CharField(choices=[('flipbook', 'Flipbook'), ('pdf', 'PDF')], max_length=10)),
                ('sinopse', models.TextField()),
                ('imagens', models.ImageField(upload_to='imagens_livro/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='livro',
            options={'ordering': ['numero_pagina']},
        ),
        migrations.RemoveField(
            model_name='livro',
            name='imagens',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='modo_leitura',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='sinopse',
        ),
        migrations.AddField(
            model_name='livro',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='paginas_livro/'),
        ),
        migrations.AddField(
            model_name='livro',
            name='numero_pagina',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='tipo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='Titulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paginas', to='livro3d.modoleitura'),
        ),
        migrations.DeleteModel(
            name='Pagina',
        ),
    ]
