# Generated by Django 5.2.1 on 2025-12-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro3d', '0002_alter_image_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sobre',
            name='galeria',
        ),
        migrations.RemoveField(
            model_name='sobre',
            name='membros',
        ),
        migrations.AddField(
            model_name='sobre',
            name='objetivo_1',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='sobre',
            name='objetivo_2',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='sobre',
            name='objetivo_3',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
