# Generated by Django 5.2.1 on 2025-07-31 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro3d', '0003_modoleitura_alter_livro_options_remove_livro_imagens_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paginas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='admistracao_page/')),
            ],
        ),
        migrations.RemoveField(
            model_name='livro',
            name='Titulo',
        ),
        migrations.RemoveField(
            model_name='membro',
            name='descricao',
        ),
        migrations.AddField(
            model_name='livro',
            name='paginas',
            field=models.ImageField(blank=True, null=True, upload_to='admistracao_page/'),
        ),
        migrations.DeleteModel(
            name='ModoLeitura',
        ),
        migrations.AddField(
            model_name='livro',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
