# Generated by Django 5.2.1 on 2025-12-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro3d', '0003_index_divosoria_index_divosoria_texto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='index',
            old_name='divosoria_texto',
            new_name='divisoria_texto',
        ),
        migrations.RenameField(
            model_name='index',
            old_name='divosoria',
            new_name='divisoria_titulo',
        ),
        migrations.RenameField(
            model_name='sobre',
            old_name='paginaTitulo',
            new_name='frase_inicio',
        ),
        migrations.RemoveField(
            model_name='sobre',
            name='secaoTitulo',
        ),
        migrations.RemoveField(
            model_name='sobre',
            name='sobre_nos',
        ),
        migrations.RemoveField(
            model_name='sobre',
            name='sobre_o_livro',
        ),
        migrations.AddField(
            model_name='membro',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='membros_imgs/'),
        ),
        migrations.AddField(
            model_name='sobre',
            name='sessao_foto',
            field=models.ImageField(blank=True, null=True, upload_to='sobre_imgs/'),
        ),
        migrations.AddField(
            model_name='sobre',
            name='sessao_texto',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='sobre',
            name='sessao_titulo',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.CreateModel(
            name='ModoLeitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frase_inicio', models.CharField(blank=True, max_length=255, null=True)),
                ('sessao_titulo', models.CharField(blank=True, max_length=300, null=True)),
                ('sessao_texto', models.CharField(blank=True, max_length=2000, null=True)),
                ('galeria', models.ManyToManyField(related_name='galeria', to='livro3d.image')),
            ],
        ),
    ]
