# Generated by Django 5.2.1 on 2025-12-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro3d', '0003_remove_sobre_galeria_remove_sobre_membros_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identidadevisual',
            name='cor_hover',
            field=models.CharField(default='#6ea3ff', max_length=7),
        ),
        migrations.AlterField(
            model_name='identidadevisual',
            name='cor_secundaria',
            field=models.CharField(default='#5b85ce', max_length=7),
        ),
    ]
