# Generated by Django 5.2.1 on 2025-12-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro3d', '0004_rename_divosoria_texto_index_divisoria_texto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modoleitura',
            name='sessao_texto',
        ),
        migrations.RemoveField(
            model_name='modoleitura',
            name='sessao_titulo',
        ),
        migrations.AlterField(
            model_name='sobre',
            name='galeria',
            field=models.ManyToManyField(related_name='galeria_sobre', to='livro3d.image'),
        ),
    ]
