# Generated by Django 5.2.1 on 2025-07-31 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro3d', '0004_paginas_remove_livro_titulo_remove_membro_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='saibamais',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
