# Generated by Django 5.2.1 on 2025-12-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro3d', '0004_rename_divosoria_texto_index_divisoria_texto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sobre',
            name='galeria',
            field=models.ManyToManyField(blank=True, null=True, related_name='galeria_sobre', to='livro3d.image'),
        ),
    ]
