# Generated by Django 5.2.1 on 2025-12-22 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro3d', '0004_alter_identidadevisual_cor_hover_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='logo',
            new_name='imagem_footer',
        ),
    ]
