# Generated by Django 5.2.1 on 2025-07-31 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro3d', '0005_homepage_saibamais'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='imagem',
            new_name='capa',
        ),
    ]
