# Generated by Django 5.2.1 on 2025-07-31 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro3d', '0006_rename_imagem_livro_capa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paginas',
        ),
        migrations.AlterModelOptions(
            name='livro',
            options={},
        ),
        migrations.RemoveField(
            model_name='livro',
            name='capa',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='numero_pagina',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='paginas',
        ),
    ]
