# Generated by Django 5.2.1 on 2025-07-31 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro3d', '0007_delete_paginas_alter_livro_options_remove_livro_capa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paginas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capa', models.ImageField(upload_to='paginas_livro/')),
                ('numero_pagina', models.IntegerField()),
                ('pagina', models.ImageField(upload_to='admistracao_page/')),
            ],
            options={
                'ordering': ['numero_pagina'],
            },
        ),
    ]
