# Generated by Django 5.2.1 on 2025-07-31 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro3d', '0008_paginas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paginas',
            name='capa',
        ),
        migrations.AddField(
            model_name='livro',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='paginas_livro/'),
        ),
    ]
