# Generated by Django 5.2.1 on 2025-07-31 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro3d', '0009_remove_paginas_capa_livro_capa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pagina', models.IntegerField()),
                ('pagina', models.ImageField(upload_to='administracao_page/')),
            ],
            options={
                'ordering': ['numero_pagina'],
            },
        ),
        migrations.DeleteModel(
            name='Paginas',
        ),
    ]
