# Generated by Django 5.2.1 on 2025-08-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro3d', '0010_pagina_delete_paginas'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='oqueeositeTit',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='saibamaisTit',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='pagina',
            name='capaCostas',
            field=models.ImageField(blank=True, null=True, upload_to='capas/'),
        ),
        migrations.AddField(
            model_name='pagina',
            name='capaFrente',
            field=models.ImageField(blank=True, null=True, upload_to='capas/'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='administracao_page/'),
        ),
        migrations.AlterField(
            model_name='pagina',
            name='pagina',
            field=models.ImageField(upload_to='paginas_livro/'),
        ),
    ]
