# Generated by Django 5.2.1 on 2025-08-04 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro3d', '0011_homepage_oqueeositetit_homepage_saibamaistit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='imgs',
            field=models.ImageField(blank=True, null=True, upload_to='galeria_sobre/'),
        ),
    ]
