# Generated by Django 5.2.1 on 2025-08-04 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro3d', '0012_livro_imgs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagina',
            name='capaCostas',
        ),
        migrations.RemoveField(
            model_name='pagina',
            name='capaFrente',
        ),
    ]
