# Generated by Django 5.2.1 on 2025-08-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro3d', '0013_remove_pagina_capacostas_remove_pagina_capafrente'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModoLeitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pageTitulo', models.TextField(max_length=100)),
                ('cardTitulo', models.TextField()),
                ('descricao', models.TextField()),
                ('pdf', models.FileField(upload_to='livro_pdf')),
            ],
        ),
        migrations.AddField(
            model_name='sobre',
            name='paginaTit',
            field=models.TextField(default='padrao', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sobre',
            name='secaoTit',
            field=models.TextField(default='nonee', max_length=200),
            preserve_default=False,
        ),
    ]
