# Generated by Django 5.2.1 on 2025-09-18 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro3d', '0014_modoleitura_sobre_paginatit_sobre_secaotit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sobre',
            old_name='paginaTit',
            new_name='paginaTitulo',
        ),
        migrations.RenameField(
            model_name='sobre',
            old_name='secaoTit',
            new_name='secaoTitulo',
        ),
    ]
