# Generated by Django 5.2.1 on 2025-09-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro3d', '0015_rename_paginatit_sobre_paginatitulo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagina',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='paginas_livro/'),
        ),
        migrations.AddField(
            model_name='pagina',
            name='costas',
            field=models.ImageField(blank=True, null=True, upload_to='paginas_livro/'),
        ),
    ]
