# Generated by Django 5.2.1 on 2025-09-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro3d', '0016_pagina_capa_pagina_costas'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='costas',
            field=models.ImageField(blank=True, null=True, upload_to='administracao_page/'),
        ),
    ]
