# Generated by Django 5.2.1 on 2025-09-23 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro3d', '0017_livro_costas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagina',
            name='capa',
        ),
        migrations.RemoveField(
            model_name='pagina',
            name='costas',
        ),
    ]
