# Generated by Django 5.2.1 on 2025-09-23 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro3d', '0018_remove_pagina_capa_remove_pagina_costas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModoLeitura',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='costas',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='imgs',
        ),
        migrations.AddField(
            model_name='livro',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='livro_pdf'),
        ),
    ]
