# Generated by Django 5.2.1 on 2025-12-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro3d', '0020_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentidadeVisual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor_principal', models.CharField(default='#005EFF', max_length=7)),
                ('cor_secundaria', models.CharField(default='#005EFF', max_length=7)),
                ('cor_hover', models.CharField(default='#005EFF', max_length=7)),
            ],
        ),
    ]
